-- TripSync UPI/manual-confirmation migration.
-- Run once in the Supabase SQL Editor. Existing rows are preserved.
-- Precheck production status type and constraints before running this script.
-- If status is an enum, run the two ALTER TYPE statements generated by:
-- SELECT format('ALTER TYPE %I.%I ADD VALUE IF NOT EXISTS %L;', udt_schema, udt_name, value)
-- FROM information_schema.columns, (VALUES ('payment_initiated'), ('awaiting_receiver_confirmation')) values(value)
-- WHERE table_schema = 'public' AND table_name = 'payments' AND column_name = 'status';

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS upi_id VARCHAR(255);
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS settlement_key VARCHAR(180);
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reference_id VARCHAR(80);
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS amount_paise BIGINT;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS initiated_at TIMESTAMPTZ;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS claimed_paid_at TIMESTAMPTZ;

UPDATE public.payments
SET amount_paise = ROUND(amount * 100)::BIGINT
WHERE amount_paise IS NULL AND amount IS NOT NULL;

DO $$
DECLARE
  invalid_count BIGINT;
BEGIN
  SELECT COUNT(*) INTO invalid_count
  FROM public.payments
  WHERE amount IS NOT NULL
    AND (amount_paise IS NULL OR amount_paise <> ROUND(amount * 100)::BIGINT);
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Migration stopped: % payment rows have invalid amount_paise values.', invalid_count;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.payments'::regclass
      AND conname = 'payments_amount_paise_positive'
  ) THEN
    ALTER TABLE public.payments ADD CONSTRAINT payments_amount_paise_positive
      CHECK (amount_paise IS NULL OR amount_paise > 0) NOT VALID;
  END IF;
END $$;
ALTER TABLE public.payments VALIDATE CONSTRAINT payments_amount_paise_positive;

-- Enum status columns need new enum values; text-like columns use a CHECK.
DO $$
DECLARE
  status_schema TEXT;
  status_name TEXT;
  is_enum BOOLEAN;
BEGIN
  SELECT c.udt_schema, c.udt_name, t.typtype = 'e'
  INTO status_schema, status_name, is_enum
  FROM information_schema.columns c
  JOIN pg_type t ON t.typname = c.udt_name
  WHERE c.table_schema = 'public'
    AND c.table_name = 'payments'
    AND c.column_name = 'status'
    AND t.typnamespace = (quote_ident(c.udt_schema) || '.' || quote_ident(c.udt_name))::regnamespace;

  IF is_enum THEN
    RAISE EXCEPTION 'payments.status is enum %.%. Run the ALTER TYPE statements in this file outside a DO block, then rerun the migration.', status_schema, status_name;
  ELSE
    -- Only the known legacy constraint is replaced. Unknown constraints remain untouched.
    ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_status_check;
    ALTER TABLE public.payments ADD CONSTRAINT payments_status_check
      CHECK (status IN ('pending', 'payment_initiated', 'awaiting_receiver_confirmation', 'completed'));
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS payments_reference_id_unique
  ON public.payments(reference_id)
  WHERE reference_id IS NOT NULL;

DO $$
DECLARE
  duplicate_count BIGINT;
BEGIN
  SELECT COUNT(*) INTO duplicate_count
  FROM (
    SELECT trip_id, from_username, to_username
    FROM public.payments
    WHERE status IN ('pending', 'payment_initiated', 'awaiting_receiver_confirmation')
    GROUP BY trip_id, from_username, to_username
    HAVING COUNT(*) > 1
  ) duplicates;
  IF duplicate_count > 0 THEN
    RAISE EXCEPTION 'Migration stopped: % duplicate active payer/receiver pairs exist.', duplicate_count;
  END IF;
END $$;

DROP INDEX IF EXISTS payments_one_active_settlement;
CREATE UNIQUE INDEX payments_one_active_settlement
  ON public.payments(trip_id, from_username, to_username)
  WHERE status IN ('pending', 'payment_initiated', 'awaiting_receiver_confirmation');

-- Verification queries: duplicate and invalid-amount queries must return zero rows.
SELECT column_name, data_type, udt_name, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'payments'
ORDER BY ordinal_position;

SELECT conname, pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conrelid = 'public.payments'::regclass;

SELECT indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'payments';

SELECT trip_id, from_username, to_username, COUNT(*) AS active_count
FROM public.payments
WHERE status IN ('pending', 'payment_initiated', 'awaiting_receiver_confirmation')
GROUP BY trip_id, from_username, to_username
HAVING COUNT(*) > 1;

SELECT id, amount, amount_paise
FROM public.payments
WHERE amount IS NOT NULL
  AND (amount_paise IS NULL OR amount_paise <> ROUND(amount * 100)::BIGINT);